### ISSUE TITLE
pthread lib is missing

### ISSUE THREAD

**Issue by angrave** [s-macke/jor1k#10]
The link library for pthreads is missing from the gcc image hdgcc.bz2
Steps to reproduce:
gcc -pthread hello.c

**Comment by regular** [comment]
Is the UART problem solved by now?

**Comment by s-macke** [comment]
Yes, the problem was solved a long time ago by me. Actually almost everything important has changed since this issue.

**Comment by benjamincburns** [comment]
@s-macke - Probably another one that can be closed?

Also re: 10MB binary files, this [announcement from GitHub](https://github.com/blog/2069-git-large-file-storage-v1-0) seems relevant.

**Comment by s-macke** [comment]
Yes, this issue can be closed
