### ISSUE TITLE
top line is the same as second line in the terminal

### ISSUE THREAD

**Issue by dugoh** [s-macke/jor1k#102]
Steps:
```sh
rm -rf jor1k jor1k-sysroot jor1k-master jor1k-sysroot-master
lynx -source https://github.com/s-macke/jor1k/archive/master.tar.gz|gunzip -c|tar -xvf -
# currently 4fc8dfedef
mv jor1k-master jor1k
cd jor1k
./compile
cd ..
lynx -source http://jor1k.com/jor1k/bin/or1k/vmlinux.bin.bz2 >./jor1k/bin/or1k/vmlinux.bin.bz2
```
In the simple demo, run seq 1 1 23

Results:
 * Expected: 
```sh
1
2
3
[snip]
```
 * Actual:
```sh
2
2
3
[snip]
```
Environment:
  * Operating system
Some mac
  * Browser
Up to date chrome

**Comment by prannoy** [comment]
Hello @dugoh , I was trying to add a buffer to the terminal and this issue seems to have come up because of one of my previous commits. I have found the reason behind this, should be fixed in the next commit.

**Comment by dugoh** [comment]
Fixed, thanks!
