### ISSUE TITLE
Strange files in jor1k-sysroot

### ISSUE THREAD

**Issue by dugoh** [s-macke/jor1k#128]
The /usr/include/bits directory has 3 sockets in it that should be normal header files. Under /usr/share/X11/locale/... are another 3 sockets that should be XI18N object tables.

This is the first time I ever got this one out of gcc:

`/usr/include/sys/resource.h:18:27: fatal error: /usr/include/bits/resource.h: No such device or address`

**Comment by s-macke** [comment]
The files have a size of zero in the filesystem
https://github.com/s-macke/jor1k-sysroot/blob/master/fs.json
and are supposed to have zero size. So the question is why the virtio/9p filesystem thinks that these are sockets.

**Comment by s-macke** [comment]
Fixed.
