### ISSUE TITLE
tmux want not go from 4.4.0 to 5.8.0 in jor1k

### ISSUE THREAD

**Issue by pflegende** [s-macke/jor1k#159]
thats not literally an "issue"
more a question for a hint to a solution
using tmux also in the new so beautifully nice
upgraded jor1k-kernel

at the moment tmux not want to say "helo" to me ...

```

~ $ uname -a
--
Linux openrisc 5.8.0+ #1 Sun Aug 16 19:03:47 CEST 2020 openrisc GNU/Linux
~ $ PATH=/bin:/usr/bin:/sbin:/usr/sbin
~ $ tmux
~ $ tmux new -s se1 -n mW1\; split-window -d
~ $ date 
Mon Aug 31 23:37:20 UTC 2020
~ $ su -c 'tmux new -s se1 -n mW1\; split-window -d '
~ $

```

in the old version 
(on same time) it's running (e.g. tmux), 
and surprisingly (for the last years) tmux was and is running without parameters on blank startet jor1k (openrisc 4.4.0)

```
Linux openrisc 4.4.0-42578-gacba10ee627d-dirty #6 Thu May 25 20:53:14 UTC 2017 openrisc GNU/Linux
```

would be nice to leave the old version without upgrading / without touch 
:) 
because it is sometimes essential for experimenting to have a splitted screen (by tmux e.g.)
and it would also be interesting to compare something between
the "old" openrisc 4.4.0 and the "new" 5.8.0
... a little bit wurmhole playing on the jor1k-time-ride-bycicle ...
;)

**HOPING for long living project jor1k**

thx
:)

PS:
may be, the new kernel does something to the "old" aplication/tool - landscape around?

**Comment by s-macke** [comment]
Maybe it is not the Linux kernel, but musl, which I also updated.
The detection of the ttyname right now looks like

https://github.com/ifduyue/musl/blob/master/src/unistd/ttyname_r.c

I wonder, why it does fail in my case.

**Comment by s-macke** [comment]
I have fixed musl. Please try again.

**Comment by pflegende** [comment]
Great! And awesome.
Now the tmux is running again and we can share screen by tmux over wireguard pockets.
Ingredible!
thx to munich. many times. Cool and good job done.


![Opera Momentaufnahme_2020-09-08_035129_s-macke github io](https://user-images.githubusercontent.com/52720420/92425209-d8986880-f186-11ea-9fd6-ffa75d2e6c8a.png)
