### ISSUE TITLE
Feaure: Filebased device driver ;use LocalStorage/BrowserFS ; a sketch

### ISSUE THREAD

**Issue by angrave** [s-macke/jor1k#16]
Some initial thoughts on how to implement a browser-backed filesystem.
i.e. files stored in Linux are just file entries stored inside the browser.

Use BrowserFS that amongst other things, wraps LocalStorage and provides a nodejs-style filesystem API
https://github.com/jvilk/BrowserFS/blob/master/README.md
http://nodejs.org/api/fs.html
BrowserFS supports directories, lazy-loading from a remote server, basic inode properties, filesystem operations (lstat,fstat,mkdir,...)
https://github.com/jvilk/BrowserFS/wiki/Using-BrowserFS

Sync and Async versions of most fs calls are available.

How? We need two portions- 
A linux device driver that talks to a custom device a new filesystem memory-mapped device (similar to ata.js / uart.js) that calls out to BrowserFS.

The device driver could be written starting from wrapfs. Not sure if wrapfs from 1999 is still relevant or useful but (from first glance) it appears to implement some of the heavy lifting.
 - or we just program directly against linux vfs API

http://wrapfs.filesystems.org/
http://git.fsl.cs.sunysb.edu/?p=wrapfs-latest.git;a=blob;f=Documentation/filesystems/wrapfs.txt
http://www.linuxjournal.com/article/6485?page=0,0

Useful - 
http://www.filesystems.org/docs/wrapfs/wrapfs.pdf

We will need to define the device interface and need to decide if we want to support async operations. Here's a rough sketch of a ticket-based system (this is to allow eventual async operations)

+0 Ticket-Command
+4 Operation (0=read,1=write,2=...)
+8 Status (0=Queued,1=Complete,2=Panic/Abnormal abort)
+C API result return_val_a (value or address if result data >32 bits)
+10 -1f unused
+20 param32_a (value or real-address)
+24 param32_b (value or address)
+28 param32_c (value or address)
+100-10ff Reserve 4K Page for big i/o
 
If the device is sync, then we could assume the results are immediately available for reading in the return val register. For results that return more than 32 bits, this value could point to a struct (possibly inside the device driver memory space or inside kernel ram)

For async operation - 
Ticket-Command could include a ticket command[8bits] and a new ticket number [24 bits]
There are only Four ticket commands -
Device Reset
New-Ticket ;
Status-Check - want to read the status/output of an existing ticket
Retire Ticket nnnn; no longer care about ticket nnnn; can discard results.

For sync commands you can declare that tickets are automatically retired when a new ticket is created.

So an idea to explore:  pointers would be pass real-address rather than copying data into the memory space of the device.
Anyway, this is just a sketch. I look forward to developing this further.

Background reading on Linux VFS
http://www.win.tue.nl/~aeb/linux/lk/lk-8.html
http://www.tldp.org/LDP/khg/HyperNews/get/fs/vfstour.html
http://www.tldp.org/LDP/lki/lki-3.html

**Comment by benjamincburns** [comment]
@s-macke Can maybe close this one?
