### ISSUE TITLE
Hostname file

### ISSUE THREAD

**Issue by 7exe** [s-macke/jor1k#161]
Hello, I've been trying to set the hostname to a custom string on boot for a while now, but it has come to my attention that there is no /etc/hostname file, So I tried to add one, which did not change it. so I checked /proc/sys/kernel/hostname, and there it was, but from where did it set it? Because I could not find any files that could've set it to "openrisc".

This is more of a question than a bug, any help would be appreciated, thanks.

**Comment by benjamincburns** [comment]
This likely has the details that you're looking for: https://kerneltalks.com/linux/all-you-need-to-know-about-hostname-in-linux/
