### ISSUE TITLE
starting from several ip over a range of some days: no lease

### ISSUE THREAD

**Issue by pflegende** [s-macke/jor1k#164]
try to connect in the 10.5.*.* network,
checking ping 8.8.8.8 
reloading some times (F5),
using different hosts with fix ip or dynamic;
but also after some days it was allways the same:

`no lease`

is it only temporary down?

**Comment by s-macke** [comment]
@benjamincburns can you check the proxy server, please.

**Comment by pflegende** [comment]
... ok, I will try it again.
.
Last result was:
in every try - jor1k system loads ok, every inside runs ok, only "no lease"
.
the 3 different hosts it runs on:
2x different fix ip (may be with proxy, but if so: different proxy; but could not touch it)
2x dyn ip (no update, nothing changed since last lease through jor1k)
(1x VPN)
everytime same result
.
I understand it so, from munich it runs ok?
I try all again.
:)

**Comment by benjamincburns** [comment]
This is my fault, sorry. The certificate has expired and I need to fix certbot but haven't had a chance to do so yet. Hopefully I can fix this in a day or two. Sorry for the inconvenience.

**Comment by pflegende** [comment]
@benjamincburns
... not at all, 
very nice to hear that it would run again.
Be calm and do not things too hurry ..
;)

@s-macke  
thank you, for calling Benjamin.
:)

**Comment by benjamincburns** [comment]
Apparently my `certbot` was old enough that it didn't have ACMEv2 support. A `sudo apt upgrade -y && sudo certbot renew` took care of it. Looks to be all good now.

![image](https://user-images.githubusercontent.com/803016/128023651-e04a87b1-afc2-44b2-bfbe-3eb2ccaa49ac.png)

**Comment by pflegende** [comment]
I appreciate your feedback.

ho, ho ...
## runs very well 
I love it, stable over 8(?) years, several browser types. For kids and grandmothers. Also with kernel update and adding WireGuard and much more by @s-macke . And with Benjamins, now for next 8 years, everrunning `certbot`. 

You made my day.



![image](https://user-images.githubusercontent.com/52720420/128026167-8c5fb875-aaaf-429d-8a79-1465b5119a79.png)


***
