### ISSUE TITLE
seems the WAN connection is lost since some hours, may be like 2021 in #164

### ISSUE THREAD

**Issue by pflegende** [s-macke/jor1k#173]
since 5 or 6 hours the internet is gone from jor1k:

ping to 10.5.0.1 is fine but not outside like 8.8.8.8 or others.
Also with telnet or ssh: nothing outside.

the screen now:
![Opera Momentaufnahme_2022-07-26_233928_s-macke github io](https://user-images.githubusercontent.com/52720420/181118450-a8f612d4-07a1-413a-9f4d-ea47a50ae986.png)

May be, something like:

# #164
---
This is my fault, sorry. The certificate has expired and I need to fix certbot but haven't had a chance to do so yet. Hopefully I can fix this in a day or two. Sorry for the inconvenience.

_Originally posted by @benjamincburns in https://github.com/s-macke/jor1k/issues/164#issuecomment-890643728_

**Comment by pflegende** [comment]
the global project:
https://twitter.com/pflegedissens/status/1552051463744094209
;)

**Comment by benjamincburns** [comment]
@pflegende Please don't stalk people on twitter for things like this. Hijacking other comment threads is quite rude.

**Comment by benjamincburns** [comment]
This is not an issue with jor1k, so I'm closing this. Please watch benjamincburns/websockproxy#10 for updates.

**Comment by pflegende** [comment]
I am very sorry that it came across as rude behavior. The comment about the wind power seemed inviting as a fun trigger for the jokingly assumed power failure. Should only be a joke regarding the debate on wind power that is also ongoing here and at the same time take away any sharpness from the request. 

I'm so sorry!
