### ISSUE TITLE
python module loading issue

### ISSUE THREAD

**Issue by amasad** [s-macke/jor1k#39]
Can't import modules in Python. Try `import time`.

For context, I'm shopping around for new ways to run interpreters in JavaScript. We implemented the original emscripten Python, Ruby, and Lua for [repl.it](http://repl.it) but now would love to have I/O support and update the interpreters which could be hard in emscripten. 

Anyways, this looks awesome, would love to use it.

**Comment by ysangkok** [comment]
importing [`__future__`](https://docs.python.org/2/library/__future__.html) still hangs Python... Simplejson requires `__future__`.

**Comment by s-macke** [comment]
The __future__ library is there, but it cannot be loaded on github pages because it starts with two underscores __future__.py.

I fixed this problem with the following patch
https://github.com/s-macke/jor1k-sysroot/commit/66673787286c171e6915abd2ea8c6f929a7cca64

**Comment by ysangkok** [comment]
Thanks!
