### ISSUE TITLE
Kernel panic while deleting directory tree

### ISSUE THREAD

**Issue by ysangkok** [s-macke/jor1k#41]
This is reproducible for me. I can supply more details if you cannot reproduce.
1. download `https://pypi.python.org/packages/source/s/simplejson/simplejson-3.6.5.tar.gz` to host machine
2. upload the file to the emulator
3. extract it using `tar xf simplejson-3.6.5.tar.gz`
4. delete the directory using `rm -rf simplejson-3.6.5`
5. kernel panic

**Comment by s-macke** [comment]
Yes, I know this error for month now and couldn't find the problem, even after several hours of searching. It is somewhere in the virtio/9p part. What I know is, that this also happens with an emulated x86 CPU, but my implementation of virtio/9p.
At the moment my best guess is, that there is an error in the Linux kernel and that I trigger it somehow.
Virtio expects, that the hardware directly manipulate some Linux structures in memory, which is kind of crazy.

There are a lot of patches available for the 3.19 kernel. 
http://lkml.iu.edu/hypermail/linux/kernel/1412.1/02488.html
After the new kernel is released I will test it with those changes.

**Comment by dugoh** [comment]
Can you share the current kernel .config?

**Comment by ysangkok** [comment]
@dugoh here it is: jor1k.com/or1k-toolchain.tar.bz2

in patches/linux/CONFIG_LINUX

**Comment by dugoh** [comment]
That's more like it (compared to the one in jor1k-toolchain-builder), thx!

**Comment by s-macke** [comment]
The repository is outdated, but links in the readme to the newest toolchain file.

**Comment by s-macke** [comment]
Tried 3.19-rc3. No luck.

**Comment by socketpair** [comment]
@s-macke you mention "emulated x86 CPU" what does this mean ? Qemu ? jor1k, that emulates x86 instead of OpenRISC ?

**Comment by s-macke** [comment]
This one:
https://github.com/copy/v86

**Comment by ysangkok** [comment]
Closing this bug since #124 contains a simpler reproduction.
