### ISSUE TITLE
ReferenceError: DebugMessage is not defined

### ISSUE THREAD

**Issue by ysangkok** [s-macke/jor1k#42]
When running some code that crashes because it needs too much memory, I get this error. This seems to be the source: [worker/messagehandler.js](https://github.com/s-macke/jor1k/blob/d31dcc8571b2686373dad8a4479a868b705efe2f/js/worker/messagehandler.js#L21)

In the master [Debug, not DebugMessage is used](https://github.com/s-macke/jor1k/blob/a5f457cf687057eab59dbc30368f2033c4f96756/js/master/messagehandler.js#L24).

**Comment by s-macke** [comment]
Yes, the function name is wrong.
Fix: https://github.com/s-macke/jor1k/commit/801ec44d2f800785f6c4dcc225ab769882f6923c
