### ISSUE TITLE
Terminal colors bugs when scrolling up in GNU Screen

### ISSUE THREAD

**Issue by ysangkok** [s-macke/jor1k#46]
To reproduce:

1. start GNU Screen using `screen`, press enter to close the intro screen
1. run `seq 0 100`
1. go to copy mode using `ctrl-a` and then `[`
1. press the up key until only the previous page is visible
1. the background is all white, but it shouldn't be

After scrolling back down, the screen remains white. After exiting copy mode, the next commands have the correct color.

**Comment by s-macke** [comment]
Possible, to figure out the correct behavior of the terminal is mainly trial and error thing. There is no doc (except other source code), which defines the behavior correctly.

**Comment by s-macke** [comment]
fixed
b1d35bfc76d085bfb48cdfdd81f9bb309181e99a
