### ISSUE TITLE
Seeking and writing isn't working

### ISSUE THREAD

**Issue by ysangkok** [s-macke/jor1k#52]
To reproduce:

```sh
cd /usr/share/mplayer
su
printf '\xff' | dd conv=notrunc skip=1 bs=1 of=orion_1.mpg
```

Expected: `dd` shows one byte written
Actual: `dd` writes 0 bytes

Note: if I specify `skip=0`, one byte is written, as it should.

Also, by verifying with `head -c32 orion_1.mpg | hd`, I can see that `dd` doesn't lie about not having written anything.

**Comment by s-macke** [comment]
I can reproduce the problem.

**Comment by s-macke** [comment]
My Linux machine here behaves the same.
So the problem might not be jor1k related.

**Comment by s-macke** [comment]
Can you try "seek=1" instead of "skip=1"

**Comment by ysangkok** [comment]
Ah, yes. Reporting bugs too late in the night I guess... :weary:  Sorry.
