### ISSUE TITLE
hangs during boot ??

### ISSUE THREAD

**Issue by moodz** [s-macke/jor1k#61]
Nice project ... tried local hosting on IIS and on hosted  ( litespeed ) .. the page loads up OK and commences to boot but then hangs. Same on win7 ( chrome,IE, firefox), OSX ( chrome, firefox ) android ... reloaded from Github multiple times but still hangs during kernel boot and not at the same point everytime. The "official" site works  works/boots fine though.

**Comment by s-macke** [comment]
All the browsers come with a security feature, that disables the loading of binary files from a local folder. 
You have either disable this feature or run the files from a local web server. Under windows, you can take http://www.rejetto.com/hfs/ for example. 
If you use Chrome, you can disable the security feature by starting Chrome with the parameter "--disable-web-security"

**Comment by moodz** [comment]
Hi .. thanks for that ...  however I am getting the same behaviour from 3 completely different installs ( ie different machines / networks / software - tested on windows / linux / android ) 
 ... only your demo site fully loads OK ( so I figure its not my security settings - or your demo site would not load ? )

I have a test URL at www.beepstick.com/jor1k

8:06:12 AM 127.0.0.1:55899 Requested GET /
8:08:31 AM 127.0.0.1:56033 Requested GET /
8:08:35 AM 127.0.0.1:56034 Requested GET /jor1k-master/
8:08:35 AM 127.0.0.1:56034 Requested GET /jor1k-master/demos/main.html
8:08:35 AM 127.0.0.1:56034 Requested GET /jor1k-master/demos/css/default.css
8:08:35 AM 127.0.0.1:56033 Requested GET /jor1k-master/demos/images/globe.png
8:08:35 AM 127.0.0.1:56034 Requested GET /jor1k-master/demos/images/upload.png
8:08:35 AM 127.0.0.1:56033 Fully downloaded - 6.22 K @ 228 KB/s - /jor1k-master/demos/images/globe.png
8:08:35 AM 127.0.0.1:56039 Requested GET /jor1k-master/bin/jor1k-master-min.js
8:08:35 AM 127.0.0.1:56034 Fully downloaded - 4.11 K @ 140 KB/s - /jor1k-master/demos/images/upload.png
8:08:35 AM 127.0.0.1:56040 Requested GET /jor1k-master/demos/images/tar.png
8:08:35 AM 127.0.0.1:56040 Fully downloaded - 437 @ 34 KB/s - /jor1k-master/demos/images/tar.png
8:08:35 AM 127.0.0.1:56039 Fully downloaded - 54.92 K @ 1607 KB/s - /jor1k-master/bin/jor1k-master-min.js
8:08:35 AM 127.0.0.1:56041 Requested GET /jor1k-master/demos/images/sync.png
8:08:35 AM 127.0.0.1:56041 Fully downloaded - 679 @ 27 KB/s - /jor1k-master/demos/images/sync.png
8:08:35 AM 127.0.0.1:56042 Requested GET /jor1k-master/demos/images/fullscreen.png
8:08:35 AM 127.0.0.1:56042 Fully downloaded - 2.40 K @ 410 KB/s - /jor1k-master/demos/images/fullscreen.png
8:08:35 AM 127.0.0.1:56042 Requested GET /jor1k-master/bin/jor1k-worker-min.js
8:08:35 AM 127.0.0.1:56042 Fully downloaded - 330.69 K @ 10923 KB/s - /jor1k-master/bin/jor1k-worker-min.js
8:08:35 AM 127.0.0.1:56042 Requested GET /jor1k-master/bin/vmlinux.bin.bz2
8:08:35 AM 127.0.0.1:56041 Requested GET /jor1k-master/bin/basefs.json
8:08:35 AM 127.0.0.1:56041 Fully downloaded - 1.99 K @ 157 KB/s - /jor1k-master/bin/basefs.json
8:08:36 AM 127.0.0.1:56041 Requested GET /jor1k-master/bin/sysroot/bin/busybox.bz2
8:08:36 AM 127.0.0.1:56039 Requested GET /jor1k-master/bin/sysroot/etc/nsswitch.conf
8:08:36 AM 127.0.0.1:56040 Requested GET /jor1k-master/bin/sysroot/etc/group
8:08:36 AM 127.0.0.1:56034 Requested GET /jor1k-master/bin/sysroot/etc/fstab
8:08:36 AM 127.0.0.1:56033 Requested GET /jor1k-master/bin/sysroot/etc/inittab
8:08:36 AM 127.0.0.1:56039 Fully downloaded - 134 @ 4 KB/s - /jor1k-master/bin/sysroot/etc/nsswitch.conf
8:08:36 AM 127.0.0.1:56040 Fully downloaded - 31 @ 1 KB/s - /jor1k-master/bin/sysroot/etc/group
8:08:36 AM 127.0.0.1:56034 Fully downloaded - 174 @ 6 KB/s - /jor1k-master/bin/sysroot/etc/fstab
8:08:36 AM 127.0.0.1:56033 Fully downloaded - 234 @ 8 KB/s - /jor1k-master/bin/sysroot/etc/inittab
8:08:36 AM 127.0.0.1:56039 Requested GET /jor1k-master/bin/sysroot/etc/host.conf
8:08:36 AM 127.0.0.1:56040 Requested GET /jor1k-master/bin/sysroot/etc/inetd.conf
8:08:36 AM 127.0.0.1:56034 Requested GET /jor1k-master/bin/sysroot/etc/passwd
8:08:36 AM 127.0.0.1:56033 Requested GET /jor1k-master/bin/sysroot/etc/network/interfaces
8:08:36 AM 127.0.0.1:56039 Fully downloaded - 27 @ 0 KB/s - /jor1k-master/bin/sysroot/etc/host.conf
8:08:36 AM 127.0.0.1:56040 Fully downloaded - 59 @ 1 KB/s - /jor1k-master/bin/sysroot/etc/inetd.conf
8:08:36 AM 127.0.0.1:56039 Requested GET /jor1k-master/bin/sysroot/etc/init.d/rcS
8:08:36 AM 127.0.0.1:56034 Fully downloaded - 137 @ 1 KB/s - /jor1k-master/bin/sysroot/etc/passwd
8:08:36 AM 127.0.0.1:56040 Requested GET /jor1k-master/bin/sysroot/etc/services
8:08:36 AM 127.0.0.1:56034 Requested GET /jor1k-master/bin/sysroot/root/profile
8:08:36 AM 127.0.0.1:56033 Fully downloaded - 64 @ 1 KB/s - /jor1k-master/bin/sysroot/etc/network/interfaces
8:08:36 AM 127.0.0.1:56042 Fully downloaded - 1.97 M @ 5893 KB/s - /jor1k-master/bin/vmlinux.bin.bz2
8:08:36 AM 127.0.0.1:56033 Requested GET /jor1k-master/bin/sysroot/usr/share/udhcpc/default.script
8:08:36 AM 127.0.0.1:56039 Fully downloaded - 966 @ 5 KB/s - /jor1k-master/bin/sysroot/etc/init.d/rcS
8:08:36 AM 127.0.0.1:56040 Fully downloaded - 18.39 K @ 96 KB/s - /jor1k-master/bin/sysroot/etc/services
8:08:36 AM 127.0.0.1:56034 Fully downloaded - 473 @ 2 KB/s - /jor1k-master/bin/sysroot/root/profile
8:08:36 AM 127.0.0.1:56033 Fully downloaded - 1.25 K @ 10 KB/s - /jor1k-master/bin/sysroot/usr/share/udhcpc/default.script
8:08:36 AM 127.0.0.1:56042 Requested GET /jor1k-master/bin/sysroot/usr/bin/showmenu
8:08:36 AM 127.0.0.1:56042 Fully downloaded - 9.45 K @ 1076 KB/s - /jor1k-master/bin/sysroot/usr/bin/showmenu
8:08:36 AM 127.0.0.1:56039 Requested GET /jor1k-master/bin/sysroot/usr/bin/help
8:08:36 AM 127.0.0.1:56039 Fully downloaded - 6.79 K @ 632 KB/s - /jor1k-master/bin/sysroot/usr/bin/help
8:08:36 AM 127.0.0.1:56041 Fully downloaded - 611.65 K @ 1347 KB/s - /jor1k-master/bin/sysroot/bin/busybox.bz2
