### ISSUE TITLE
network support down

### ISSUE THREAD

**Issue by trabitboy** [s-macke/jor1k#65]
Hello,
network support appears not to work;
is the demo server down,
or is it something custom to the environment I am running in ?
I am investigating hosting a version at home :)
( Kudos on this AWESOME project )

**Comment by s-macke** [comment]
Hi, actually it is still working. However it doesn't support a ssl connection. Google changed their algorithms, so that https is preferred over http. That means, that a direct search in google finally leads to the github https website.
Unfortunately that means, that any further connections like websockets are denied by the web browser when it is not encrypted. I will ask the relay operator, what we can do to solve this issue.

**Comment by trabitboy** [comment]
Thanks for the quick reply !
Actually I can't get any connection at all;
to make sure very basic network is working ,
shouldn't ping www.google.com work ?
# sorry for eventual noobness #
I tested that websocket works from here,
but only with secure websocket 
( http://www.websocket.org/echo.html )

**Comment by s-macke** [comment]
Yes, ping to www.google.com should work. And I tried it 1 minute ago with Firefox, IE and Chrome in Windows. No problem. You are definitely on this page? http://s-macke.github.io/jor1k/demos/main.html
And not on https://s-macke.github.io/jor1k/demos/main.html ?

You can take a look at the console/debug output of your browser. Maybe there is some error message.

**Comment by s-macke** [comment]
The relay is ws://relay.widgetry.org/
But it might be, that other websites than the official one are not allowed to access the network. 
Also for me the echo test it not working.

**Comment by trabitboy** [comment]
hello,
ping doesn't work and actually,
I have a ton of websocket errors in the console :)
I'll try to setup a websocket connection from here to my home server to understand the ins and outs .

![websocket](https://cloud.githubusercontent.com/assets/110751/7387897/4ef9fbda-ee61-11e4-9174-787fdd7868eb.png)

**Comment by trabitboy** [comment]
Is there a way I can assert / test the websocket aspect by typing a function call in the debug console ?
( simulate a connect, simulate a send )
I realize I should read the code to find this :)

**Comment by ysangkok** [comment]
@trabitboy: Try this: https://www.websocket.org/echo.html (remember to
check the TLS box or it won't connect)

**Comment by trabitboy** [comment]
The echo test works ( I posted a bit earlier about it )

**Comment by ysangkok** [comment]
Could it be that your network has a proxy intercepting and altering your traffic? This often happens in corporate settings or if you have a router capable of filtering cookies. HTTPS traffic wouldn't be affected because the router can't generate valid certificates, so it doesn't even try to alter it.

**Comment by trabitboy** [comment]
Yes connection goes through an http proxy;
that's why I wanted to setup a node.js websocket server at home and see if I can get it to work.

**Comment by s-macke** [comment]
A few days ago, I changed the behavior of the websocket. It tries only to connect three times and then give up. Every time it writes the whole websocket object on the console. 
https://github.com/s-macke/jor1k/commit/e293ef2b38562683d22d0fc7c1e59629206e7533
The source code is in this file:
https://github.com/s-macke/jor1k/blob/master/js/master/dev/ethernet.js

**Comment by s-macke** [comment]
To trigger the opening of the websocket you can try to execute: 
    jor1kgui.ethernet.OpenSocket()
in the console. You can also type
    jor1kgui.ethernet.url
to get the url.

**Comment by trabitboy** [comment]
Thanks ! 
Actually it fails with a 403 :) 

When I look at the network view on http://www.websocket.org/echo.html,
it's the same ( http gets a 403 but the https returns fine ) .

So it just needs an https server;
there is nothing "really blocking or bug " .

**Comment by benjamincburns** [comment]
Sorry it has taken me so long to respond. I'm the guy who runs the relay. I have just enabled support on the relay and have pushed the change to master. I'm about to push the change to the github.io branch which connects using a secure websocket.

As an added bonus, this will make the virtual network behave a lot more like a VPN, as all traffic in/out of the relay server will be encrypted.

**Comment by benjamincburns** [comment]
Looks like everything is sorted now. SSL support enabled in `gh-pages` and `master`. Please reopen issue if I missed something.
